spring:
  application:
    name: Financial_Wunderwaffe_Server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/Financial_Wunderwaffe_DataBase
    username: root
    password: My7Pass@Word_9_8A_zE

#logging:
#  level:
#    root: debug

server:
  port: 8080